# Generated by Django 3.2.3 on 2022-02-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mycompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='companyPic')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('skey', models.CharField(blank=True, max_length=300, null=True)),
                ('pkey', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
