# Generated by Django 3.2.3 on 2022-02-27 19:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='productPic')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vfile', models.FileField(blank=True, null=True, upload_to='productVideo')),
                ('reg_price', models.FloatField()),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('mft_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='business.mycompany')),
            ],
        ),
    ]
