# Generated by Django 3.2.3 on 2022-03-05 03:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('sugar', models.IntegerField(blank=True, default=0, null=True)),
                ('milk', models.IntegerField(blank=True, default=0, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product')),
            ],
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('street_name', models.CharField(max_length=50)),
                ('appartment_num', models.PositiveIntegerField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('order_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Inprocess', 'Inprocess'), ('Confirmed', 'Confirmed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Inprocess', max_length=50)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.shippingaddress')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
                ('products', models.ManyToManyField(to='business.Cartitem')),
                ('stripepayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripepayments', to='business.stripepayment')),
            ],
        ),
    ]
