# Generated by Django 3.2.3 on 2022-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_shippingaddress_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='appartment_num',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
