# Generated by Django 3.2.3 on 2022-03-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20220305_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripepayment',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='buyer',
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypayment', to='business.order'),
        ),
    ]
