# Generated by Django 3.2.3 on 2022-03-17 01:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/EmployeePic/')),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='EmpoResume')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.mycompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
